#!/bin/sh

# Copyright (c) 2012
# See LICENSE for details.
#
# Dave Murphy <davem@devkitpro.org>
# Israel Jacques <mrko@eecs.berkeley.edu>

# Look for automated configuration file to bypass prompts
[ -f 'config' ] && . './config' || panic "Configuration file 'config' not found" 1
[ -f 'scripts/utils' ] && . './scripts/utils' || exit 1

clean_up () {
    ! test -z "${BUILD_SRC_DIR}" \
        || exit 1

    message "Cleaning up '${BUILD_SRC_DIR}'"

    rm -r -f \
        "${BUILD_SRC_DIR}/binutils" \
        "${BUILD_SRC_DIR}/gcc" \
        "${BUILD_SRC_DIR}/newlib" \
        "${BUILD_SRC_DIR}/gdb" \
        "${BUILD_SRC_DIR}/${BINUTILS_SRC_DIR}" \
        "${BUILD_SRC_DIR}/${GCC_SRC_DIR}" \
        "${BUILD_SRC_DIR}/${NEWLIB_SRC_DIR}" \
        "${BUILD_SRC_DIR}/${GDB_SRC_DIR}" \
        "${BUILD_SRC_DIR}/built-binutils" \
        "${BUILD_SRC_DIR}/built-gcc" \
        "${BUILD_SRC_DIR}/built-g++" \
        "${BUILD_SRC_DIR}/built-newlib" \
        "${BUILD_SRC_DIR}/built-gdb" \
        "${BUILD_SRC_DIR}/configured-binutils" \
        "${BUILD_SRC_DIR}/configured-gcc" \
        "${BUILD_SRC_DIR}/configured-newlib" \
        "${BUILD_SRC_DIR}/configured-gdb" \
        "${BUILD_SRC_DIR}/installed-binutils" \
        "${BUILD_SRC_DIR}/installed-gcc" \
        "${BUILD_SRC_DIR}/installed-g++" \
        "${BUILD_SRC_DIR}/installed-newlib" \
        "${BUILD_SRC_DIR}/installed-gdb" \
        "${BUILD_SRC_DIR}/extracted" \
        "${BUILD_SRC_DIR}/applied-patches"

    exit ${1}
}

trap 'clean_up 1' 2 9 15

TARGET='sh-elf'
PREFIX="${BUILD_INSTALL_DIR}/${TARGET}"

# Sane defaults for building toolchain
CFLAGS="-O2 -pipe"
export "CFLAGS"
CXXFLAGS="${CFLAGS}"
export "CXXFLAGS"
unset "LDFLAGS"

# Add installed devkit to the path, adjusting path on minsys
PATH="${BUILD_INSTALL_DIR}/${TARGET}/bin:${PATH}"
export "PATH"

# Ask whether to download the source packages or not
GCC_CORE="gcc-core-${GCC_VERSION}.tar.bz2"
GNU_URL="ftp://ftp.gnu.org/gnu"
GCC_CORE_URL="${GNU_URL}/gcc/gcc-${GCC_VERSION}/${GCC_CORE}"
GCC_GPP="gcc-g++-${GCC_VERSION}.tar.bz2"
GCC_GPP_URL="${GNU_URL}/gcc/gcc-${GCC_VERSION}/${GCC_GPP}"
GCC_SRC_DIR="gcc-${GCC_VERSION}"

BINUTILS="binutils-${BINUTILS_VERSION}.tar.bz2"
BINUTILS_URL="$GNU_URL/binutils/${BINUTILS}"
BINUTILS_SRC_DIR="binutils-${BINUTILS_VERSION}"

GDB="gdb-${GDB_VERSION}.tar.bz2"
GDB_URL="${GNU_URL}/gdb/${GDB}"
GDB_SRC_DIR="gdb-${GDB_VERSION}"

NEWLIB_URL="ftp://sources.redhat.com/pub/newlib"
NEWLIB="newlib-${NEWLIB_VERSION}.tar.gz"
NEWLIB_URL="${NEWLIB_URL}/${NEWLIB}"
NEWLIB_SRC_DIR="newlib-${NEWLIB_VERSION}"

# Get preferred installation directory and set paths to the sources
[ ! -z "${BUILD_INSTALL_DIR}" ] && \
    mkdir -p "${BUILD_INSTALL_DIR}" && \
    # Make sure we have the proper permissions
    touch "${BUILD_INSTALL_DIR}/non-existent-file" && \
    rm "${BUILD_INSTALL_DIR}/non-existent-file" || \
    panic "Invalid install path" 1

cd "${BUILD_SRC_DIR}/"
rm -f "binutils.log" \
    "gcc.log" \
    "gdb.log" \
    "newlib.log"
if [ "${BUILD_DOWNLOAD}" = "no" ]; then
    [ ! -f "${BINUTILS}" ] && \
        panic "'${BINUTILS}' not found in ${BUILD_SRC_DIR}" 1

    [ ! -f "${GCC_CORE}" ] && \
        panic "'${GCC_CORE}' not found in ${BUILD_SRC_DIR}" 1

    [ ! -f "${GCC_GPP}" ] && \
        panic "'${GCC_GPP}' not found in ${BUILD_SRC_DIR}" 1

    [ ! -f "${GDB}" ] && \
        panic "'${GDB}' not found in ${BUILD_SRC_DIR}" 1

    [ ! -f "${NEWLIB}" ] && \
        panic "'${NEWLIB}' not found in ${BUILD_SRC_DIR}" 1
else
    ! FETCH="`command -v "wget"`" && panic "Cannot find 'wget'" 1

    if [ ! -f "${BINUTILS}" ]; then
        message "Downloading '${BINUTILS}'"
        ("${FETCH}" "${BINUTILS_URL}") 1>> "binutils.log" 2>&1 || panic "Failed to download ${BINUTILS}" 1
    fi

    if [ ! -f "${GCC_CORE}" ]; then
        message "Downloading '${GCC_CORE}'"
        ("${FETCH}" "${GCC_CORE_URL}")  1>> "gcc.log" 2>&1 || panic "Failed to download ${GCC_CORE}" 1
    fi

    if [ ! -f "${GCC_GPP}" ]; then
        message "Downloading '${GCC_GPP}'"
        ("${FETCH}" "${GCC_GPP_URL}") 1>> "gcc.log" 2>&1 || panic "Failed to download ${GCC_GPP}" 1
    fi

    if [ ! -f "${GDB}" ]; then
        message "Downloading '${GDB}'"
        ("${FETCH}" "${GDB_URL}") 1>> "gdb.log" 2>&1 || panic "Failed to download ${GDB}" 1
    fi

    if [ ! -f "${NEWLIB}" ]; then
        message "Downloading '${NEWLIB}'"
        ("${FETCH}" "${NEWLIB_URL}") 1>> "newlib.log" 2>&1 || panic "Failed to download ${NEWLIB}" 1
    fi
fi
cd "${OLDPWD}"

# Find proper 'make'
[ -z "${MAKE}" -a -x "`which 'gnumake'`" ] && MAKE="`which 'gnumake'`"
[ -z "${MAKE}" -a -x "`which 'gmake'`" ] && MAKE="`which 'gmake'`"
[ -z "${MAKE}" -a -x "`which 'make'`" ] && MAKE="`which 'make'`"
[ -z "${MAKE}" ] && panic "'make' not found in \$PATH" 1
export "MAKE"

# Find proper 'awk'
[ -z "${GAWK}" -a -x "`which 'gawk'`" ] && GAWK="`which 'gawk'`"
[ -z "${GAWK}" -a -x "`which 'awk'`" ] && GAWK="`which 'awk'`"
[ -z "${GAWK}" ] && panic "'awk' not found in \$PATH" 1
export "GAWK"

# Find 'makeinfo' (needed for Newlib)
[ ! -x "`which 'makeinfo'`" ] && panic "'makeinfo' not found in \$PATH" 1

# Extract source packages
cd "${BUILD_SRC_DIR}"
if [ ! -f 'extracted' ]; then
    message "Extracting '${BINUTILS}'"
    tar -xjf "${BUILD_SRC_DIR}/${BINUTILS}" || panic "Extracting ${BINUTILS}" 1

    message "Extracting '$GCC_CORE'"
    tar -xjf "${BUILD_SRC_DIR}/${GCC_CORE}" || panic "Extracting ${GCC_CORE}" 1

    message "Extracting '${GCC_GPP}'"
    tar -xjf "${BUILD_SRC_DIR}/${GCC_GPP}" || panic "Extracting ${GCC_GPP}" 1

    message "Extracting '${NEWLIB}'"
    tar -xzf "${BUILD_SRC_DIR}/${NEWLIB}" || panic "Extracting ${NEWLIB}" 1

    message "Extracting '${GDB}'"
    tar -xjf "${BUILD_SRC_DIR}/${GDB}" || panic "Extracting ${GCC_GPP}" 1

    touch "${BUILD_SRC_DIR}/extracted"
fi
cd "${OLDPWD}"

# Apply patches
if [ -f "${TARGET}/scripts/patch" ]; then
    . "${TARGET}/scripts/patch" || panic "Error building cross-compiler" 1
fi

# Build and install cross-compiler components
if [ -f "${TARGET}/scripts/build" ]; then
    . "${TARGET}/scripts/build" || panic "Error building cross-compiler" 1
fi
cd "${OLDPWD}"

# Strip debug info from libraries
find "${BUILD_INSTALL_DIR}/${TARGET}/lib/gcc/${TARGET}" -name "*.a" -exec "${TARGET}"-strip -d {} \;
find "${BUILD_INSTALL_DIR}/${TARGET}/${TARGET}" -name "*.a" -exec "${TARGET}"-strip -d {} \;

# Clean up temporary files and source directories
clean_up 0

message "Add path '${BUILD_INSTALL_DIR}/${TARGET}/bin' to your \$PATH environment variable"
