#!/bin/sh
current=$1
# check for previous versions
echo "The following files have not been updated for $current"
grep -L $current NEWS ChangeLog genromfs.lsm genromfs.8 && echo "(all ok)"
# find -type f|xargs egrep '(0\.3|0\.5|0\.5.1)'
exit 0
