#!/bin/sh

# Copyright (c) 2012
# See LICENSE for details.
#
# Dave Murphy <davem@devkitpro.org>
# Israel Jacquez <mrkotfw@gmail.com>

# Build and install Binutils
mkdir -p "${BUILD_SRC_DIR}/${M68K_TARGET}/binutils"
cd "${BUILD_SRC_DIR}/${M68K_TARGET}/binutils"
if [ ! -f "${BUILD_SRC_DIR}/${M68K_TARGET}/configured-binutils" ]; then
    message "Configuring Binutils"
    (CFLAGS="" LDFLAGS="" ../"${BINUTILS_SRC_DIR}"/configure \
        --disable-debug \
        --disable-nls \
        --disable-shared \
        --disable-threads \
        --prefix="${BUILD_INSTALL_DIR}/${M68K_TARGET}" \
        --target="${M68K_TARGET}" \
        --with-gcc \
        --with-gnu-as \
        --with-gnu-ld \
        --with-stabs) 1>> "${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log" 2>&1 \
        || panic "See '${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${M68K_TARGET}/configured-binutils"
fi

if [ ! -f "${BUILD_SRC_DIR}/${M68K_TARGET}/built-binutils" ]; then
    message "Building Binutils"
    ("${MAKE}") 1>> "${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${M68K_TARGET}/built-binutils"
fi

if [ ! -f "${BUILD_SRC_DIR}/${M68K_TARGET}/installed-binutils" ]; then
    message "Installing Binutils"
    ("${MAKE}" install) 1>> "${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/binutils-${M68K_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${M68K_TARGET}/installed-binutils"
fi
cd "${OLDPWD}"
