#!/bin/sh

# Copyright (c) 2012-2016
# See LICENSE for details.
#
# Dave Murphy <davem@devkitpro.org>
# Israel Jacquez <mrkotfw@gmail.com>

# Build and install Binutils
mkdir -p "${BUILD_SRC_DIR}/${SH_TARGET}/binutils"
cd "${BUILD_SRC_DIR}/${SH_TARGET}/binutils"
if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/configured-binutils" ]; then
    message "Configuring Binutils"
    CFLAGS="" LDFLAGS="" ../"${BINUTILS_SRC_DIR}"/configure \
        --prefix="${BUILD_INSTALL_DIR}/${SH_TARGET}" \
        --target="${SH_TARGET}" \
        --disable-werror \
        --disable-debug \
        --disable-shared \
        --disable-threads \
        --with-gcc \
        --with-gnu-as \
        --with-gnu-ld \
        --with-stabs 1>> "${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log" 2>&1 \
        || panic "See '${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/configured-binutils"
fi

if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/built-binutils" ]; then
    message "Building Binutils"
    "${MAKE}" -j ${BUILD_MAKE_JOBS} 1>> "${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/built-binutils"
fi

if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/installed-binutils" ]; then
    message "Installing Binutils"
    "${MAKE}" -j ${BUILD_MAKE_JOBS} install 1>> "${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/installed-binutils"
fi
cd "${OLDPWD}"


# Build and install just the C compiler
mkdir -p "${BUILD_SRC_DIR}/${SH_TARGET}/gcc"
cd "${BUILD_SRC_DIR}/${SH_TARGET}/gcc"
gcc_configure_options=(
        --prefix="${BUILD_INSTALL_DIR}/${SH_TARGET}" \
        --target="${SH_TARGET}" \
        --program-prefix="${SH_TARGET}-" \
        --with-endian=big \
        --with-cpu=m2 \
        --disable-cld \
        --disable-initfini-array \
        --disable-largefile \
        --disable-libstdcxx-pch \
        --disable-multilib \
        --disable-objc-gc \
        --disable-rpath \
        --disable-shared \
        --disable-threads \
        --disable-tls \
        --disable-win32-registry \
        --disable-decimal-float \
        --disable-frame-pointer \
        --disable-fixed-point \
        --enable-languages=c,c++ \
        --enable-static \
        --disable-fdpic \
        --disable-default-pie \
        --disable-libquadmath \
        --disable-libquadmath-support \
        --disable-libvtv \
        --disable-libgomp \
        --disable-libssp \
        --disable-libada \
        --with-gcc \
        --with-gnu-as \
        --with-gnu-ld \
        --without-dwarf2 \
        --without-headers \
        --without-newlib
        MAKEINFO=missing)
if ! [ -z "${BUILD_SUPPORT_LIBS}" ]; then
    gcc_configure_options+=(
        --with-gmp="${BUILD_SUPPORT_LIBS}" \
        --with-mpfr="${BUILD_SUPPORT_LIBS}" \
        --with-mpc="${BUILD_SUPPORT_LIBS}")
fi
if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/configured-gcc" ]; then
    message "Configuring GCC"
    CFLAGS="" \
    LDFLAGS="" \
    CFLAGS_FOR_TARGET="-O2 -m2 -mb -fomit-frame-pointer" \
    LDFLAGS_FOR_TARGET="" ../"${GCC_SRC_DIR}"/configure \
        ${gcc_configure_options[@]} 1>> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log" 2>&1 \
        || panic "See '${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/configured-gcc"
fi

if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/built-gcc" ]; then
    message "Building GCC"
    "${MAKE}" -j ${BUILD_MAKE_JOBS} all-gcc 1>> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log" 2>&1 \
        || panic "See '${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/built-gcc"
fi

if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/installed-gcc" ]; then
    message "Installing GCC"
    "${MAKE}" -j ${BUILD_MAKE_JOBS} install-gcc 1>> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log" 2>&1 \
        || panic "See '${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/installed-gcc"
fi
unset "CFLAGS"
cd "${OLDPWD}"


# Build and install the final compiler
cd "${BUILD_SRC_DIR}/${SH_TARGET}/gcc"
if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/built-g++" ]; then
    message "Building GCC"
    "${MAKE}" -j ${BUILD_MAKE_JOBS} 1>> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/built-g++"
fi

if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/installed-g++" ]; then
    message "Installing GCC"
    ("${MAKE}" -j ${BUILD_MAKE_JOBS} install) 1>> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log" 2>&1 || \
        panic "See '${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log'" 1
    touch "${BUILD_SRC_DIR}/${SH_TARGET}/installed-g++"
fi
cd "${OLDPWD}"


# Build and install GDB
if [[ "${OPTION_ENABLE_GDB}" == "yes" ]]; then
    mkdir -p "${BUILD_SRC_DIR}/${SH_TARGET}/gdb"
    cd "${BUILD_SRC_DIR}/${SH_TARGET}/gdb"
    if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/configured-gdb" ]; then
        message "Configuring GDB"
        CFLAGS="" LDFLAGS="" ../"${GDB_SRC_DIR}"/configure \
            --disable-werror \
            --prefix="${BUILD_INSTALL_DIR}/${SH_TARGET}" \
            --target="${SH_TARGET}" 1>> "${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log" 2>&1 \
            || panic "See '${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log'" 1
        touch "${BUILD_SRC_DIR}/${SH_TARGET}/configured-gdb"
    fi

    if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/built-gdb" ]; then
        message "Building GDB"
        "${MAKE}" -j ${BUILD_MAKE_JOBS} 1>> "${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log" 2>&1 || \
            panic "See '${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log'" 1
        touch "${BUILD_SRC_DIR}/${SH_TARGET}/built-gdb"
    fi

    if [ ! -f "${BUILD_SRC_DIR}/${SH_TARGET}/installed-gdb" ]; then
        message "Installing GDB"
        "${MAKE}" -j ${BUILD_MAKE_JOBS} install 1>> "${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log" 2>&1 || \
            panic "See '${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log'" 1
        touch "${BUILD_SRC_DIR}/${SH_TARGET}/installed-gdb"
    fi
    cd "${OLDPWD}"
fi
