include ../../pre.common.mk

PROJECT:= inkfill
OBJECTS+= \
	root.romdisk.o \
	fs.o \
	game-inkfill.o \
	game-over.o \
	game.o \
	globals.o \
	scene.o \
	title.o \
	tutorial.o

include ../../post.common.mk
