include ../../pre.common.mk

PROJECT:= inkfill
LIBRARIES:= tga
###OBJECTS:= $(INSTALL_ROOT)/sh-elf/lib/crt0.o $(INSTALL_ROOT)/sh-elf/lib/crt0-init.o
OBJECTS:= \
	root.romdisk.o \
	fs.o \
	game-over.o \
	game.o \
	globals.o \
	inkfill.o \
	scene.o \
	title.o \
	tutorial.o

include ../../post.common.mk
