#!/bin/sh

# Extract source packages
mkdir -p "${BUILD_SRC_DIR}/${SH_TARGET}"
cd "${BUILD_SRC_DIR}/${SH_TARGET}"
if [ ! -f 'extracted' ]; then
    message "Extracting '${BINUTILS}'"
    tar -xjf "${BUILD_SRC_DIR}/${BINUTILS}" || panic "Extracting ${BINUTILS}" 1

    message "Extracting '$GCC'"
    tar -xjf "${BUILD_SRC_DIR}/${GCC}" || panic "Extracting ${GCC}" 1

    message "Extracting '${NEWLIB}'"
    tar -xzf "${BUILD_SRC_DIR}/${NEWLIB}" || panic "Extracting ${NEWLIB}" 1

    message "Extracting '${GDB}'"
    tar -xjf "${BUILD_SRC_DIR}/${GDB}" || panic "Extracting ${GCC_GDB}" 1

    if [ "${OPTION_ENABLE_DDD}" = "yes" ]; then
        message "Extracting '${DDD}'"
        tar -xzf "${BUILD_SRC_DIR}/${DDD}" || panic "Extracting ${GCC_DDD}" 1
    fi

    touch "${BUILD_SRC_DIR}/${SH_TARGET}/extracted"
fi
cd "${OLDPWD}"
