#!/bin/sh

# Copyright (c) 2012
# See LICENSE for details.
#
# Israel Jacquez <mrkotfw@gmail.com>

> "${BUILD_SRC_DIR}/binutils-${SH_TARGET}.log"
> "${BUILD_SRC_DIR}/ddd-${SH_TARGET}.log"
> "${BUILD_SRC_DIR}/gcc-${SH_TARGET}.log"
> "${BUILD_SRC_DIR}/gdb-${SH_TARGET}.log"
> "${BUILD_SRC_DIR}/newlib-${SH_TARGET}.log"
