#!/bin/sh

# Extract source packages
mkdir -p "${BUILD_SRC_DIR}/${M68K_TARGET}"
cd "${BUILD_SRC_DIR}/${M68K_TARGET}"
if [ ! -f "extracted-binutils" ]; then
    message "Extracting '${BINUTILS}'"
    rm -r -f binutils
    rm -r -f binutils-${BINUTILS_VERSION}
    if ! tar -xjf "${BUILD_SRC_DIR}/${BINUTILS}" > /dev/null 2>&1; then
        panic "Extracting ${BINUTILS}" 1
    fi
    touch "extracted-binutils"
fi
cd "${OLDPWD}"
