include ../../pre.common.mk

PROJECT:= vdp1
OBJECTS+= \
	root.romdisk.o \
	fs.o \
	globals.o \
	state.o \
	state_machine.o \
	test.o \
	tests.o \
	vdp1.o \
	tests/primitives/normal_sprite/00.o \
	tests/primitives/scaled_sprite/00.o \
	tests/primitives/scaled_sprite/01.o

CFLAGS+=-I.

include ../../post.common.mk
