include ../../pre.common.mk

PROJECT:= vdp1
OBJECTS+= \
	root.romdisk.o \
	fs.o \
	globals.o \
	state.o \
	state_machine.o \
	test.o \
	tests/00.o \
	tests/01.o \
	tests/02.o \
	tests/03.o \
	tests/04.o \
	tests/05.o \
	tests/06.o \
	tests/07.o \
	vdp1.o

include ../../post.common.mk
