#!/bin/sh

# Copyright (c) 2012-2014
# See LICENSE for details.
#
# Israel Jacquez <mrkotfw@gmail.com>

PROGNAME="${0##*/}"

function panic () {
    printf -- "${PROGNAME}: Error: ${1}\n" >&2
    exit ${2}
}

if [ ${#} != 1 ]; then
    echo "Usage: ${PROGNAME} file-list output-file\n" >&2
    exit 2
fi

image="${1}"

if [ ! -d "cd" ]; then
    panic "Directory \`cd' does not exist" 1
fi

genisoimage \
    -quiet \
    -sysid "SEGA SEGASATURN" \
    -volid "" \
    -volset "" \
    -publisher "SEGA ENTERPRISES, LTD." \
    -preparer "SEGA ENTERPRISES, LTD." \
    -appid "SEGA ENTERPRISES, LTD." \
    -abstract "ABS.TXT" \
    -copyright "CPY.TXT" \
    -biblio "BIB.TXT" \
    -generic-boot 'ip.bin' \
    -iso-level 1 \
    -input-charset iso8859-1  \
    -no-bak \
    -m '.*' \
    -o "${image}.iso" \
    cd
