#!/bin/sh

# Copyright (c) 2012-2014
# See LICENSE for details.
#
# Israel Jacquez <mrkotfw@gmail.com>

PROGNAME="${0##*/}"

panic() {
    printf -- "${PROGNAME}: Error: ${1}\n" >&2
    exit ${2}
}

if [ ${#} != 1 ]; then
    printf -- "Usage: ${PROGNAME} image-output-name\n" >&2
    exit 2
fi

image="${1}"

if [ ! -d "./cd" ]; then
    panic "Directory \`cd' does not exist in \`.'" 1
fi

# Check if all the files are present
for file in "./cd/ABS.TXT" "./cd/BIB.TXT" "./cd/CPY.TXT" "./IP.BIN"; do
    if [ -f "${file}" ]; then
        continue
    fi
    panic "File \``basename "${file}"`' does not exist in \``dirname "${file}"`'" 1
done

genisoimage \
    -quiet \
    -sysid "SEGA SEGASATURN" \
    -volid "" \
    -volset "" \
    -publisher "SEGA ENTERPRISES, LTD." \
    -preparer "SEGA ENTERPRISES, LTD." \
    -appid "SEGA ENTERPRISES, LTD." \
    -abstract "ABS.TXT" \
    -copyright "CPY.TXT" \
    -biblio "BIB.TXT" \
    -generic-boot "IP.BIN" \
    -iso-level 1 \
    -input-charset iso8859-1  \
    -no-bak \
    -m '.*' \
    -o "${image}.iso" \
    cd # CD directory
