var annotated_dup =
[
    [ "color_fix16_hsv_t", "unioncolor__fix16__hsv__t.html", "unioncolor__fix16__hsv__t" ],
    [ "color_fix16_rgb", "unioncolor__fix16__rgb.html", "unioncolor__fix16__rgb" ],
    [ "color_rgb1555_t", "unioncolor__rgb1555__t.html", "unioncolor__rgb1555__t" ],
    [ "color_rgb888_t", "unioncolor__rgb888__t.html", "unioncolor__rgb888__t" ],
    [ "color_uint8_hsv_t", "unioncolor__uint8__hsv__t.html", "unioncolor__uint8__hsv__t" ],
    [ "cpu_dmac_cfg", "structcpu__dmac__cfg.html", "structcpu__dmac__cfg" ],
    [ "cpu_dmac_status", "structcpu__dmac__status.html", "structcpu__dmac__status" ],
    [ "cpu_registers", "structcpu__registers.html", "structcpu__registers" ],
    [ "cpu_smpc_time", "structcpu__smpc__time.html", "structcpu__smpc__time" ],
    [ "fix16_mat3", "unionfix16__mat3.html", "unionfix16__mat3" ],
    [ "fix16_plane", "structfix16__plane.html", "structfix16__plane" ],
    [ "fix16_vec2", "unionfix16__vec2.html", "unionfix16__vec2" ],
    [ "fix16_vec3", "unionfix16__vec3.html", "unionfix16__vec3" ],
    [ "int16_vec2_t", "structint16__vec2__t.html", "structint16__vec2__t" ],
    [ "int32_vec2_t", "structint32__vec2__t.html", "structint32__vec2__t" ],
    [ "int8_vec2_t", "structint8__vec2__t.html", "structint8__vec2__t" ],
    [ "int8_vec3_t", "structint8__vec3__t.html", "structint8__vec3__t" ],
    [ "scu_dma_handle", "structscu__dma__handle.html", "structscu__dma__handle" ],
    [ "scu_dma_level_cfg", "structscu__dma__level__cfg.html", "structscu__dma__level__cfg" ],
    [ "scu_dma_xfer", "structscu__dma__xfer.html", "structscu__dma__xfer" ],
    [ "scu_dsp_status", "structscu__dsp__status.html", "structscu__dsp__status" ],
    [ "scu_ic_priority", "structscu__ic__priority.html", "structscu__ic__priority" ]
];