var annotated_dup =
[
    [ "arp_callback_t", "structarp__callback.html", "structarp__callback" ],
    [ "bup_config_t", "structbup__config__t.html", "structbup__config__t" ],
    [ "bup_date_t", "structbup__date__t.html", "structbup__date__t" ],
    [ "bup_devices_t", "unionbup__devices__t.html", "unionbup__devices__t" ],
    [ "bup_directory_t", "structbup__directory__t.html", "structbup__directory__t" ],
    [ "bup_stat_t", "structbup__stat__t.html", "structbup__stat__t" ],
    [ "bup_t", "structbup__t.html", null ],
    [ "cpu_cache_data_line_t", "unioncpu__cache__data__line__t.html", "unioncpu__cache__data__line__t" ],
    [ "cpu_cache_data_way_t", "structcpu__cache__data__way__t.html", "structcpu__cache__data__way__t" ],
    [ "cpu_dmac_cfg_t", "structcpu__dmac__cfg__t.html", "structcpu__dmac__cfg__t" ],
    [ "cpu_dmac_status_t", "structcpu__dmac__status__t.html", "structcpu__dmac__status__t" ],
    [ "cpu_ioregs_t", "structcpu__ioregs__t.html", "structcpu__ioregs__t" ],
    [ "cpu_registers_t", "structcpu__registers__t.html", "structcpu__registers__t" ],
    [ "cpu_sci_cfg_t", "structcpu__sci__cfg__t.html", "structcpu__sci__cfg__t" ],
    [ "int16_vec2_t", "structint16__vec2__t.html", "structint16__vec2__t" ],
    [ "int32_vec2_t", "structint32__vec2__t.html", "structint32__vec2__t" ],
    [ "int8_vec2_t", "structint8__vec2__t.html", "structint8__vec2__t" ],
    [ "int8_vec3_t", "structint8__vec3__t.html", "structint8__vec3__t" ],
    [ "mat_stack_t", "structmat__stack__t.html", "structmat__stack__t" ],
    [ "scu_dma_handle_t", "structscu__dma__handle__t.html", "structscu__dma__handle__t" ],
    [ "scu_dma_level_cfg_t", "structscu__dma__level__cfg__t.html", "structscu__dma__level__cfg__t" ],
    [ "scu_dma_xfer_t", "structscu__dma__xfer__t.html", "structscu__dma__xfer__t" ],
    [ "scu_dma_xfer_type_t", "unionscu__dma__xfer__type__t.html", "unionscu__dma__xfer__type__t" ],
    [ "scu_dsp_status_t", "structscu__dsp__status__t.html", "structscu__dsp__status__t" ],
    [ "scu_ic_priority_t", "structscu__ic__priority__t.html", "structscu__ic__priority__t" ],
    [ "smpc_time_dec_t", "structsmpc__time__dec__t.html", "structsmpc__time__dec__t" ],
    [ "smpc_time_t", "structsmpc__time__t.html", "structsmpc__time__t" ],
    [ "uint8_vec2_t", "structuint8__vec2__t.html", "structuint8__vec2__t" ],
    [ "uint8_vec3_t", "structuint8__vec3__t.html", "structuint8__vec3__t" ]
];