var modules =
[
    [ "Memory map", "group__MEMORY__MAP.html", "group__MEMORY__MAP" ],
    [ "GCC", "group__GCC.html", "group__GCC" ],
    [ "SCU DMA", "group__SCU__DMA.html", "group__SCU__DMA" ],
    [ "SCU DSP", "group__SCU__DSP.html", "group__SCU__DSP" ],
    [ "SCU IC", "group__SCU__IC.html", "group__SCU__IC" ],
    [ "SCU IC Setters", "group__SCU__IC__HELPERS.html", "group__SCU__IC__HELPERS" ],
    [ "SCU Timer", "group__SCU__TIMER.html", "group__SCU__TIMER" ],
    [ "Cartridge ARP", "group__ARP.html", "group__ARP" ],
    [ "DRAM Cart", "group__DRAM__CART.html", "group__DRAM__CART" ],
    [ "CPU", "group__CPU.html", "group__CPU" ],
    [ "CPU Cache", "group__CPU__CACHE.html", "group__CPU__CACHE" ],
    [ "CPU Division Unit (DIVU)", "group__CPU__DIVU.html", "group__CPU__DIVU" ],
    [ "CPU Direct Memory Access Controller (DMAC)", "group__CPU__DMAC.html", "group__CPU__DMAC" ],
    [ "CPU Dual", "group__CPU__DUAL.html", "group__CPU__DUAL" ],
    [ "CPU Endianness", "group__CPU__ENDIANNESS.html", "group__CPU__ENDIANNESS" ],
    [ "CPU Free-Running Timer (FRT)", "group__CPU__FRT.html", "group__CPU__FRT" ],
    [ "CPU Interrupt Controller (INTC)", "group__CPU__INTC.html", "group__CPU__INTC" ],
    [ "CPU INTC Setters", "group__CPU__INTC__HELPERS.html", "group__CPU__INTC__HELPERS" ],
    [ "CPU Registers", "group__CPU__REGISTERS.html", "group__CPU__REGISTERS" ],
    [ "CPU Synchronization", "group__CPU__SYNC.html", "group__CPU__SYNC" ],
    [ "CPU Watchdog Timer (WDT)", "group__CPU__WDT.html", "group__CPU__WDT" ],
    [ "SMPC RTC", "group__SMPC__RTC.html", "group__SMPC__RTC" ],
    [ "SMPC SMC", "group__SMPC__SMC.html", "group__SMPC__SMC" ],
    [ "Math", "group__MATH.html", "group__MATH" ]
];