#!/bin/bash
{
# Copyright (c) 2012-2016
# See LICENSE for details.
#
# Israel Jacquez <mrkotfw@gmail.com>
# Dave Murphy <davem@devkitpro.org>

PROGNAME=`basename "${0}"`

CONFIG_FILENAME="config"
CONFIG_IN_FILENAME="config.in"
CONFIG_PATH="./${CONFIG_FILENAME}"

# Function message:
#   ${1} => Message
message () {
    local _message="${1}"

    printf -- "${PROGNAME}: %s\n" "${_message}"
}

# Function panic:
#   ${1} => Message
#   ${2} => Exit status code
panic() {
    local _message="${1}"
    local _exit_code=${2}

    printf -- "${PROGNAME}: Error: %s\n" "${_message}" 1>&2
    exit ${_exit_code}
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "${SOURCE}" ]; do # Resolve ${SOURCE} until the file is no longer a symlink
    ROOT="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
    SOURCE="$(readlink "${SOURCE}")"
    # If ${SOURCE} was a relative symlink, we need to resolve it
    # relative to the path where the symlink file was located
    [[ ${SOURCE} != /* ]] && SOURCE="${ROOT}/${SOURCE}"
done
ROOT="$(cd -P "$(dirname "${SOURCE}" )" && pwd)"

if [[ "${ROOT}" != "`pwd`" ]]; then
    panic "You must be in \`${ROOT}' in order to invoke ${PROGNAME}"
fi

# Look for automated configuration file
if [ -f "${CONFIG_PATH}" ]; then
    error_line=$(/usr/bin/env python << EOF
from re import match

line_no = 0
with open("${CONFIG_PATH}", "r") as f:
    for line in f.readlines():
        line_no += 1
        # Ignore comments and empty lines
        if match(r"^\s*#.*$|^\s*$", line.strip()):
            continue
        if not match(r"^[A-Z_][A-Z_0-9]+=(?:\"[^\"]*\"|[0-9]+)$", line.strip()):
            print line_no,
            raise SystemExit
EOF
)
    if [ ${?} -ne 0 ]; then
        panic "Syntax error in configuration file \`${CONFIG_FILENAME}' on line ${error_line}" 1
    fi

    source "${CONFIG_PATH}" > /dev/null 2>&1
else
    panic "Configuration file \`${CONFIG_FILENAME}' not found; see \`${CONFIG_IN_FILENAME}'" 1
fi

# Function is_set:
#   ${1} => Variable
is_set() {
    if [[ ! "${!1}" && "${!1-_}" ]]; then
        panic "Variable \"${1}\" does not exist in your config file" 1
    fi
}

# Function check_boolean:
#   ${1} => Value
check_boolean() {
    if [[ "${!1}" != "no" && "${!1}" != "yes" ]]; then
        panic "Variable \"${1}\" has an invalid value in your config file" 1
    fi
}

# Function fetch:
#   ${1} => URL
fetch() {
    local _url="${1}"

    "${FETCH}" "${FETCH_FLAGS}" "${_url}"
    local _exit_code=${?}

    case "${FETCH}" in
        wget)
            # Kludge: It looks like GNU Wget doesn't return the
            # correct exit status code.
            if [ ${_exit_code} -ge 2 ] && [ ${_exit_code} -le 8 ]; then
                return 1
            fi
            return 0
            ;;
        *)
            return ${_exit_code}
    esac
}

# Function checksum_gpg:
#   ${1} => File (.sig file)
checksum_gpg() {
    local _file="${1}"

    "${GPG}" --verify --keyring "${BUILD_SRC_DIR}/${GNU_KEYRING}" "${_file}"
    local _exit_code=${?}
    return ${_exit_code}
}

for var in \
    "OPTION_DOWNLOAD_TARBALLS" \
    "OPTION_ENABLE_GDB"; do
    is_set "${var}"
    check_boolean "${var}"
done

for var in \
    "BUILD_INSTALL_DIR" \
    "BUILD_SRC_DIR" \
    "BINUTILS_VERSION" \
    "BUILD_MAKE_JOBS" \
    "GCC_VERSION" \
    "GDB_VERSION" \
    "NEWLIB_VERSION" \
    "MAKE" \
    "AWK" \
    "GPG" \
    "MD5" \
    "PATCH" \
    "FETCH" \
    "FETCH_FLAGS"; do
    is_set "${var}"
done

# Function clean_up:
#
clean_up () {
    if [ -z "${BUILD_SRC_DIR}" ]; then
        exit 1
    fi

    message "Cleaning up '${BUILD_SRC_DIR}'"

    rm -r -f \
        "${BUILD_SRC_DIR}/${SH_TARGET}" \
        "${BUILD_SRC_DIR}/${M68K_TARGET}"
    exit 0
}

trap 'clean_up' 1 2 9 15

SH_TARGET='sh-elf'
M68K_TARGET='m68k-elf'

# Sane defaults for building toolchain
export CFLAGS="-O2 -pipe"
export CXXFLAGS="${CFLAGS}"

unset "LDFLAGS"

# Add installed devkit to the path, adjusting path on minsys
export PATH="${BUILD_INSTALL_DIR}/${SH_TARGET}/bin:${BUILD_INSTALL_DIR}/${M68K_TARGET}/bin:${PATH}"

GNU_URL="ftp://ftp.gnu.org/gnu"
SOURCES_REDHAT_URL="ftp://sources.redhat.com/pub/newlib"

GCC="gcc-${GCC_VERSION}.tar.bz2"
GCC_URL="${GNU_URL}/gcc/gcc-${GCC_VERSION}/${GCC}"
GCC_SIG="${GCC}.sig"
GCC_SIG_URL="${GNU_URL}/gcc/gcc-${GCC_VERSION}/${GCC_SIG}"
GCC_SRC_DIR="gcc-${GCC_VERSION}"

BINUTILS="binutils-${BINUTILS_VERSION}.tar.bz2"
BINUTILS_URL="${GNU_URL}/binutils/${BINUTILS}"
BINUTILS_SIG="${BINUTILS}.sig"
BINUTILS_SIG_URL="${GNU_URL}/binutils/${BINUTILS_SIG}"
BINUTILS_SRC_DIR="binutils-${BINUTILS_VERSION}"

GDB="gdb-${GDB_VERSION}.tar.bz2"
GDB_URL="${GNU_URL}/gdb/${GDB}"
GDB_SIG="${GDB}.sig"
GDB_SIG_URL="${GNU_URL}/gdb/${GDB_SIG}"
GDB_SRC_DIR="gdb-${GDB_VERSION}"

GNU_KEYRING="gnu-keyring.gpg"
GNU_KEYRING_URL="${GNU_URL}/${GNU_KEYRING}"

NEWLIB="newlib-${NEWLIB_VERSION}.tar.gz"
NEWLIB_URL="${SOURCES_REDHAT_URL}/${NEWLIB}"
NEWLIB_SRC_DIR="newlib-${NEWLIB_VERSION}"

NEWLIB_MD5="md5.sum"
NEWLIB_MD5_URL="${SOURCES_REDHAT_URL}/${NEWLIB_MD5}"

# Get preferred installation directory and set paths to the sources
# Make sure we have the proper permissions
mkdir -p "${BUILD_INSTALL_DIR}" 1> /dev/null 2>&1 && \
    test -x "${BUILD_INSTALL_DIR}" && \
    test -w "${BUILD_INSTALL_DIR}" && \
    test -r "${BUILD_INSTALL_DIR}" || \
    panic "Couldn't create install directory" 1

cd "${BUILD_SRC_DIR}/"
# Ask whether to download the source packages or not
if [[ "${OPTION_DOWNLOAD_TARBALLS}" == "no" ]]; then
    message "Be sure to have the following files in ${BUILD_SRC_DIR}:"
    printf -- "\n\t 1. ${GNU_KEYRING}"
    printf -- "\n\t 2. ${BINUTILS}"
    printf -- "\n\t 3. ${BINUTILS_SIG}"
    printf -- "\n\t 4. ${GCC}"
    printf -- "\n\t 5. ${GCC_SIG}"
    printf -- "\n\t 6. ${NEWLIB}"
    printf -- "\n\t 7. ${NEWLIB_MD5}"
    printf -- "\n\t 8. ${GDB}"
    printf -- "\n\t 9. ${GDB_SIG}"
    printf -- "\n"
    printf -- "\n"
else
    if [ ! -f "${BUILD_SRC_DIR}/downloaded-tarballs" ]; then
        message "Downloading files..."

        if [ ! -f "${BINUTILS}" ]; then
            message "Downloading \`${BINUTILS}'"
            if ! fetch "${BINUTILS_URL}" 1>> "binutils.log" 2>&1; then
                panic "Failed to download ${BINUTILS} (see \`${BUILD_SRC_DIR}/binutils.log')" 1
            fi
            if ! fetch "${BINUTILS_SIG_URL}" 1>> "binutils.log" 2>&1; then
                panic "Failed to download ${BINUTILS_SIG} (see \`${BUILD_SRC_DIR}/binutils.log')" 1
            fi
        fi

        if [ ! -f "${GCC}" ]; then
            message "Downloading \`${GCC}'"
            if ! fetch "${GCC_URL}"  1>> "gcc.log" 2>&1; then
                panic "Failed to download ${GCC} (see \`${BUILD_SRC_DIR}/gcc.log')" 1
            fi
            if ! fetch "${GCC_SIG_URL}"  1>> "gcc.log" 2>&1; then
                panic "Failed to download ${GCC_SIG} (see \`${BUILD_SRC_DIR}/gcc.log')" 1
            fi
        fi

        if [[ "${OPTION_ENABLE_GDB}" == "yes" ]]; then
            if [ ! -f "${GDB}" ]; then
                message "Downloading \`${GDB}'"
                if ! fetch "${GDB_URL}" 1>> "gdb.log" 2>&1; then
                    panic "Failed to download ${GDB} (see \`${BUILD_SRC_DIR}/gdb.log')" 1
                fi
                if ! fetch "${GDB_SIG_URL}" 1>> "gdb.log" 2>&1; then
                    panic "Failed to download ${GDB_SIG} (see \`${BUILD_SRC_DIR}/gdb.log')" 1
                fi
            fi
        fi

        if [ ! -f "${GNU_KEYRING}" ]; then
            message "Downloading \`${GNU_KEYRING}'"
            if ! fetch "${GNU_KEYRING_URL}"  1>> "gcc.log" 2>&1; then
                panic "Failed to download ${GNU_KEYRING} (see \`${BUILD_SRC_DIR}/gcc.log')" 1
            fi
            if ! fetch "${GNU_KEYRING_URL}"  1>> "gcc.log" 2>&1; then
                panic "Failed to download ${GNU_KEYRING} (see \`${BUILD_SRC_DIR}/gcc.log')" 1
            fi
        fi

        if [ ! -f "${NEWLIB}" ]; then
            message "Downloading \`${NEWLIB}'"
            if ! fetch "${NEWLIB_URL}" 1>> "newlib.log" 2>&1; then
                panic "Failed to download ${NEWLIB} (see \`${BUILD_SRC_DIR}/newlib.log')" 1
            fi
        fi

        if [ ! -f "${NEWLIB_MD5}" ]; then
            message "Downloading \`${NEWLIB_MD5}'"
            if ! fetch "${NEWLIB_MD5_URL}" 1>> "newlib.log" 2>&1; then
                panic "Failed to download ${NEWLIB_MD5} (see \`${BUILD_SRC_DIR}/newlib.log')" 1
            fi
        fi

        touch "downloaded-tarballs"
    fi
fi

if [ ! -f "${GNU_KEYRING}" ]; then
    panic "\`${GNU_KEYRING}' not found"
fi

if [ ! -f "${BINUTILS}" ]; then
    panic "\`${BINUTILS}' not found" 1
fi
if [ ! -f "${BINUTILS_SIG}" ]; then
    panic "\`${BINUTILS_SIG}' not found" 1
fi

if [ ! -f "${GCC}" ]; then
    panic "\`${GCC}' not found" 1
fi
if [ ! -f "${GCC_SIG}" ]; then
    panic "\`${GCC_SIG}' not found" 1
fi

if [ ! -f "${NEWLIB}" ]; then
    panic "'${NEWLIB}' not found" 1
fi
if [ ! -f "${NEWLIB_MD5}" ]; then
    panic "'${NEWLIB_MD5}' not found" 1
fi

if [[ "${OPTION_ENABLE_GDB}" == "yes" ]]; then
    if [ ! -f "${GDB}" ]; then
        panic "\`${GDB}' not found" 1
    fi
    if [ ! -f "${GDB_SIG}" ]; then
        panic "\`${GDB_SIG}' not found" 1
    fi
fi

if [ ! -f "checked-integrity" ]; then
    message "Checking integrity..."

    # Check integrity
    message "Checking integrity of \`${BINUTILS}'"
    if ! checksum_gpg "${BINUTILS_SIG}" 1>> "binutils.log" 2>&1; then
        panic "Integrity check for ${BINUTILS} failed (see \`${BUILD_SRC_DIR}/binutils.log')" 1
    fi

    message "Checking integrity of \`${GCC}'"
    if ! checksum_gpg "${GCC_SIG}" 1>> "gcc.log" 2>&1; then
        panic "Integrity check for ${GCC} failed (see \`${BUILD_SRC_DIR}/gcc.log')" 1
    fi

    if [[ "${OPTION_ENABLE_GDB}" == "yes" ]]; then
        message "Checking integrity of \`${GDB}'"
        if ! checksum_gpg "${GDB_SIG}" 1>> "gdb.log" 2>&1; then
            panic "Integrity check for ${GDB} failed (see \`${BUILD_SRC_DIR}/gdb.log')" 1
        fi
    fi

    # The md5.sum is a special (annoying) case
    message "Checking integrity of \`${NEWLIB}'"
    md5=`cat "${NEWLIB_MD5}" 2> /dev/null | grep "${NEWLIB}" 2> /dev/null | sed 's/[[:space:]][[:space:]]*/,/g' | cut -d ',' -f 1`
    case "${MD5}" in
        "md5")
            calculated_md5=`"${MD5}" "${NEWLIB}" | awk '{ print $1; }'`
            ;;
        "md5sum")
            calculated_md5=`"${MD5}" "${NEWLIB}" | sed -r -n 's/^([a-f0-9][a-f0-9]*)\s+.*?$/\1/pg'`
            ;;
    esac
    if [ -z "${md5}" ] || [[ "${calculated_md5}" != "${md5}" ]]; then
        panic "Integrity check for ${NEWLIB} failed" 1
    fi
    unset "md5"
    unset "calculated_md5"

    touch "checked-integrity"
fi
cd - 1> /dev/null

for target in "${SH_TARGET}" "${M68K_TARGET}"; do
    if [ -f "${BUILD_SRC_DIR}/${target}/build-complete" ]; then
        continue
    fi

    message "Building ${target} target..."

    # Begin building
    if [ -f "${target}/scripts/init" ]; then
        source "${target}/scripts/init"
    fi
    if [ -f "${target}/scripts/extract" ]; then
        source "${target}/scripts/extract"
    fi
    if [ -f "${target}/scripts/patch" ]; then
        source "${target}/scripts/patch"
    fi
    if [ -f "${target}/scripts/build" ]; then
        source "${target}/scripts/build"
    fi
    if [ -f "${target}/scripts/strip" ]; then
        source "${target}/scripts/strip"
    fi
    if [ -f "${target}/scripts/finish" ]; then
        source "${target}/scripts/finish"
    fi
done

# Clean up temporary files and source directories
clean_up
}
