#!/bin/bash

# -*- mode: sh -*-

PROGNAME="${0##*/}"

if [ -z "${YAUL_BUILD_ROOT}" ]; then
    printf -- "${PROGNAME}: Error: Undefined YAUL_BUILD_ROOT (build root directory)\n" >&2
    exit 2
fi

if ! command -v "rc" >/dev/null; then
    printf -- "${PROGNAME}: Error: executable \`rc' not found in \${PATH}\n" >&2
    exit 1
fi

if [ -n "${YAUL_RTAGS}" ]; then
    rc --project-root "${YAUL_BUILD_ROOT}" --wait --compile "${@}"
fi

compiler="${1}"
shift
exec "${compiler}" ${@}
