#!/bin/bash

# -*- mode: sh -*-

PROGNAME="${0##*/}"

if [ -z "${YAUL_BUILD_ROOT}" ]; then
    printf -- "${PROGNAME}: Error: Undefined YAUL_BUILD_ROOT (build root directory)\n" >&2
    exit 2
fi

if ! command -v "rdm" >/dev/null; then
    printf -- "${PROGNAME}: Error: executable \`rdm' not found in \${PATH}\n" >&2
    exit 1
fi

if ! command -v "rc" >/dev/null; then
    printf -- "${PROGNAME}: Error: executable \`rc' not found in \${PATH}\n" >&2
    exit 1
fi

GCC_VERSION=`${YAUL_INSTALL_ROOT}/sh-elf/bin/sh-elf-gcc --version | awk '/^sh-elf-gcc/ { print $3 }'`

rdm \
    --log-file-log-level=verbose-debug \
    --no-comments \
    --no-libclang-include-path \
    --isystem "${YAUL_INSTALL_ROOT}/sh-elf/lib/gcc/sh-elf/${GCC_VERSION}/include" \
    --isystem "${YAUL_INSTALL_ROOT}/sh-elf/sh-elf/include"
