include ../pre.common.mk

PROJECT:= game-inkfill
OBJECTS+= \
	fs.o \
	game-inkfill.o \
	game-over.o \
	game.o \
	globals.o \
	root.romdisk.o \
	scene.o \
	title.o \
	tutorial.o

include ../post.common.mk
